/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_Estudiantes;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class InformacionPersonal extends javax.swing.JPanel {

    /**
     * Creates new form InformacionPersonal
     */
    
    Controlador_Estudiantes controlador;
    public InformacionPersonal() {
        initComponents();
        deshabilitarCampos();
    }
    
    public void agregarEventos(Controlador_Estudiantes controlador)
    {
        this.controlador=controlador;
        this.btn_ConsultaRapida.addActionListener(controlador);
        this.jt_Cedula.addActionListener(controlador);
    }
    public String[] devolverInformacion()
    {
        String informacion[]=new String[3];
        informacion[0]=this.jt_Cedula.getText();
        informacion[1]=this.jt_NombreCompleto.getText();
        informacion[2]=this.jt_Direccion.getText();
        
        return informacion;
    }
    public String devolverCedula()
    {
        return this.jt_Cedula.getText();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreCompleto.setText(arreglo[0]);
        this.jt_Direccion.setText(arreglo[1]);
    }
    public void habilitarCampos()
    {
        this.jt_NombreCompleto.setEnabled(true);
        this.jt_Direccion.setEnabled(true);
    }
    public void deshabilitarCampos()
    {
        this.jt_Cedula.setEnabled(true);
        this.jt_Cedula.setText("");
        this.jt_NombreCompleto.setText("");
        this.jt_Direccion.setText("");
        this.jt_NombreCompleto.setEnabled(false);
        this.jt_Direccion.setEnabled(false);
    }
    public void habilitarEdicion()
    {
        this.jt_Cedula.setEnabled(false);
        this.jt_NombreCompleto.setEnabled(true);
        this.jt_Direccion.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_NombreCompleto = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        btn_ConsultaRapida = new javax.swing.JButton();

        setOpaque(false);
        setLayout(null);

        jl_Cedula.setText("Cédula");
        add(jl_Cedula);
        jl_Cedula.setBounds(22, 30, 39, 16);

        jl_NombreCompleto.setText("Nombre Completo");
        add(jl_NombreCompleto);
        jl_NombreCompleto.setBounds(22, 102, 103, 16);

        jl_Direccion.setText("Dirección");
        add(jl_Direccion);
        jl_Direccion.setBounds(22, 135, 52, 16);

        jt_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_CedulaKeyPressed(evt);
            }
        });
        add(jt_Cedula);
        jt_Cedula.setBounds(130, 27, 128, 22);
        add(jt_NombreCompleto);
        jt_NombreCompleto.setBounds(130, 99, 355, 22);
        add(jt_Direccion);
        jt_Direccion.setBounds(130, 132, 355, 22);

        btn_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultar.png"))); // NOI18N
        btn_ConsultaRapida.setActionCommand("Consulta_Rapida");
        btn_ConsultaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultaRapidaActionPerformed(evt);
            }
        });
        add(btn_ConsultaRapida);
        btn_ConsultaRapida.setBounds(265, 0, 103, 79);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CedulaKeyPressed

        if(evt.getKeyCode()==10)
        {
            this.controlador.buscar();
        }
    }//GEN-LAST:event_jt_CedulaKeyPressed

    private void btn_ConsultaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultaRapidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ConsultaRapidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConsultaRapida;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_NombreCompleto;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}
