/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_Cursos;

/**
 *
 * @author Sofia Elizondo y Erika Jones
 */
public class InformacionCursos extends javax.swing.JPanel {

    
    
    Controlador_Cursos controlador;
            
    public InformacionCursos() {
        initComponents();
        cargarCreditos();
        deshabilitarCampos();
    }
public void cargarCreditos()
    {
        this.jcb_Creditos.removeAllItems();
        for(int contador=0;contador<=10;contador++)
        {
            this.jcb_Creditos.addItem(""+contador);
        }
        this.jcb_Creditos.setSelectedIndex(4);
        
    }
    public void agregarEventos(Controlador_Cursos controlador)
    {
        this.controlador=controlador;
        this.btn_ConsultaRapida.addActionListener(controlador);
    }
    public String devolverSigla()
    {
        return this.jt_Sigla.getText();
    }
    public void habilitarEdicion()
    {
        this.jt_Sigla.setEnabled(false);
        this.jt_Nombre.setEnabled(true);
        this.jcb_Creditos.setEnabled(true);
        this.jt_Horario.setEnabled(true);
    }
    public void mostrarInformacion(String arreglo[])
    {
       this.jt_Sigla.setText(arreglo[0]);
        this.jt_Nombre.setText(arreglo[1]);
        this.jcb_Creditos.setSelectedIndex(Integer.parseInt(arreglo[2]));;
        this.jt_Horario.setText(arreglo[3]);
        
    }
    
    public void habilitarCampos()
    {
        this.jt_Nombre.setEnabled(true);
        this.jcb_Creditos.setEnabled(true);
        this.jt_Horario.setEnabled(true);
    }
    public String[] devolverInformacion()
    {
        String informacion[]=new String[4];
        informacion[0]=this.jt_Sigla.getText();
        informacion[1]=this.jt_Nombre.getText();
        informacion[2]=""+this.jcb_Creditos.getSelectedIndex();
        informacion[3]=this.jt_Horario.getText();
        
        return informacion;
    }
    public void deshabilitarCampos()
    {
        this.jt_Sigla.setText("");
        this.jt_Sigla.setEnabled(true);
        
        this.jt_Nombre.setText("");
        this.jt_Nombre.setEnabled(false);
        
        this.jcb_Creditos.setSelectedIndex(4);
        this.jcb_Creditos.setEnabled(false);
        
        this.jt_Horario.setText("");
        this.jt_Horario.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcb_Creditos = new javax.swing.JComboBox<String>();
        btn_ConsultaRapida = new javax.swing.JButton();
        jl_Horario = new javax.swing.JLabel();
        jt_Horario = new javax.swing.JTextField();
        jt_Sigla = new javax.swing.JTextField();
        jl_Sigla = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jl_Creditos = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jcb_Creditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jcb_Creditos);
        jcb_Creditos.setBounds(91, 112, 184, 22);

        btn_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultar.png"))); // NOI18N
        btn_ConsultaRapida.setActionCommand("ConsultaRapida");
        btn_ConsultaRapida.setContentAreaFilled(false);
        add(btn_ConsultaRapida);
        btn_ConsultaRapida.setBounds(203, 0, 72, 70);

        jl_Horario.setText("Horario");
        add(jl_Horario);
        jl_Horario.setBounds(7, 150, 60, 16);
        add(jt_Horario);
        jt_Horario.setBounds(91, 147, 184, 22);

        jt_Sigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_SiglaKeyPressed(evt);
            }
        });
        add(jt_Sigla);
        jt_Sigla.setBounds(76, 13, 115, 22);

        jl_Sigla.setText("Sigla");
        add(jl_Sigla);
        jl_Sigla.setBounds(14, 16, 50, 16);

        jl_Nombre.setText("Nombre");
        add(jl_Nombre);
        jl_Nombre.setBounds(7, 80, 60, 16);
        add(jt_Nombre);
        jt_Nombre.setBounds(70, 77, 205, 22);

        jl_Creditos.setText("Créditos");
        add(jl_Creditos);
        jl_Creditos.setBounds(7, 115, 70, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_SiglaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_SiglaKeyPressed
        if(evt.getKeyCode()==10)
        {
            this.controlador.buscar();
        } 
    }//GEN-LAST:event_jt_SiglaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConsultaRapida;
    private javax.swing.JComboBox<String> jcb_Creditos;
    private javax.swing.JLabel jl_Creditos;
    private javax.swing.JLabel jl_Horario;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Sigla;
    private javax.swing.JTextField jt_Horario;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Sigla;
    // End of variables declaration//GEN-END:variables
}
