/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_Cursos;
import Modelo.ArchivoCurso;
import Modelo.ConexionBD;
import javax.swing.JOptionPane;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class VentanaCursos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCursos
     */
     public Controlador_Cursos controlador;
    public VentanaCursos(ConexionBD conexionBD,ArchivoCurso archivoCurso) {
        initComponents();
        this.setLocation(250, 200);
        controlador=new Controlador_Cursos(this, conexionBD,archivoCurso);
        agregarEventos();
    }
    
    public void seleccionAlmacenamiento(String almacenamiento)
    {
        controlador.seleccionAlmacenamiento(almacenamiento);
        System.out.println(almacenamiento+" VentanaCursos");
    }
    
    public void agregarEventos()
    {
        this.botones2.agregarEventosCursos(controlador);
        this.informacionCursos2.agregarEventos(controlador);
    }
    public String devolverSigla()
    {
        return this.informacionCursos2.devolverSigla();
    }
    public void habilitarEdicion()
    {
        this.botones2.habilitarEdicion();
        this.informacionCursos2.habilitarEdicion();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.informacionCursos2.mostrarInformacion(arreglo);
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public void habilitarAgregar()
    {
        this.botones2.habilitarAgregar();
        this.informacionCursos2.habilitarCampos();
    }
    public String[] devolverInformacion()
    {
        return this.informacionCursos2.devolverInformacion();
    }
    public void resetearGUI()
    {
        this.botones2.deshabilitarBotones();
        this.informacionCursos2.deshabilitarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones2 = new Vista.Botones();
        informacionCursos2 = new Vista.InformacionCursos();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);
        getContentPane().add(botones2);
        botones2.setBounds(30, 380, 570, 113);
        getContentPane().add(informacionCursos2);
        informacionCursos2.setBounds(160, 180, 304, 267);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondocurso-01.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Botones botones2;
    private Vista.InformacionCursos informacionCursos2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
